apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jiv46dz2r-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-64907c9749.dcpy.p3.openshiftapps.com/rhtap/rhtap-qe:d0c5ec55f1feea2ff2d62b12be0f4ef5977f7c14@sha256:fe738ffa115b7bfb1c83856a9948e6f480588931e9e70c784fc81f6ae9f2d862
          name: container-image
